name: Java CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v2

    - name: Configurar JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: '11'

    - name: Build e Teste com Maven
      run: mvn clean install && mvn test
