name: Java CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v2

    - name: Configurar JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: '11'

    - name: Compilar e Executar Testes
      run: |
        javac -d bin src/*.java  # Compila todos os arquivos na pasta src
        java -cp bin CalculoImc  # Executa a classe principal

